// AUTO-GENERATED by scripts/generate-songs.mjs — do not hand-edit.
// Drop audio files into public/music (optionally matching artwork into public/covers,
// same filename) then re-run `npm run songs:generate`.
import type { Track } from "@/types/music";

export const songs: Track[] = [
  {
    "id": "audiocopper-dark-571483",
    "title": "audiocopper-dark-571483",
    "artist": "Unknown Artist",
    "cover": null,
    "src": "/music/audiocopper-dark-571483.mp3"
  },
  {
    "id": "grand-project-wonders-of-the-earth-550792",
    "title": "grand_project-wonders-of-the-earth-550792",
    "artist": "Unknown Artist",
    "cover": null,
    "src": "/music/grand_project-wonders-of-the-earth-550792.mp3"
  },
  {
    "id": "mickeyscat-moment-of-peace-mickeyscat-554494",
    "title": "mickeyscat-moment-of-peace-mickeyscat-554494",
    "artist": "Unknown Artist",
    "cover": null,
    "src": "/music/mickeyscat-moment-of-peace-mickeyscat-554494.mp3"
  },
  {
    "id": "sigmamusicart-football-football-music-551346",
    "title": "sigmamusicart-football-football-music-551346",
    "artist": "Unknown Artist",
    "cover": null,
    "src": "/music/sigmamusicart-football-football-music-551346.mp3"
  },
  {
    "id": "sigmamusicart-no-copyright-music-537751",
    "title": "sigmamusicart-no-copyright-music-537751",
    "artist": "Unknown Artist",
    "cover": null,
    "src": "/music/sigmamusicart-no-copyright-music-537751.mp3"
  }
];
