// Scans public/music (and matches artwork from public/covers), writes src/lib/songs.ts.
// Run manually with `npm run songs:generate`, or automatically before `npm run dev` (predev).
import { readdirSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, extname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = fileURLToPath(new URL("..", import.meta.url));
const musicDir = join(rootDir, "public", "music");
const coversDir = join(rootDir, "public", "covers");
const outFile = join(rootDir, "src", "lib", "songs.ts");

const AUDIO_EXTS = new Set([".mp3", ".wav", ".ogg", ".m4a", ".flac"]);
const COVER_EXTS = [".jpg", ".jpeg", ".png", ".webp", ".gif"];

mkdirSync(musicDir, { recursive: true });
mkdirSync(coversDir, { recursive: true });

const audioFiles = existsSync(musicDir)
  ? readdirSync(musicDir).filter((f) => AUDIO_EXTS.has(extname(f).toLowerCase()))
  : [];

const coverFiles = existsSync(coversDir) ? readdirSync(coversDir) : [];

function findCover(nameWithoutExt) {
  for (const ext of COVER_EXTS) {
    const match = coverFiles.find(
      (f) => f.toLowerCase() === `${nameWithoutExt}${ext}`.toLowerCase()
    );
    if (match) return `/covers/${match}`;
  }
  return null;
}

// Supports "Artist - Title.mp3" naming; otherwise falls back to the filename as the title.
function parseName(fileNameWithoutExt) {
  const parts = fileNameWithoutExt.split(" - ");
  if (parts.length >= 2) {
    return { artist: parts[0].trim(), title: parts.slice(1).join(" - ").trim() };
  }
  return { artist: "Unknown Artist", title: fileNameWithoutExt.trim() };
}

const songs = audioFiles
  .sort((a, b) => a.localeCompare(b))
  .map((file) => {
    const nameWithoutExt = basename(file, extname(file));
    const { artist, title } = parseName(nameWithoutExt);
    return {
      id: nameWithoutExt.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      title,
      artist,
      cover: findCover(nameWithoutExt),
      src: `/music/${file}`,
    };
  });

const banner = `// AUTO-GENERATED by scripts/generate-songs.mjs — do not hand-edit.
// Drop audio files into public/music (optionally matching artwork into public/covers,
// same filename) then re-run \`npm run songs:generate\`.
import type { Track } from "@/types/music";

export const songs: Track[] = ${JSON.stringify(songs, null, 2)};
`;

writeFileSync(outFile, banner);
console.log(`Generated ${songs.length} track(s) -> src/lib/songs.ts`);
